sp:
  user-service:
    users: "[{\"id\":77, \"username\":\"abc\",\"password\":\"666\"},{\"id\":88, \"username\":\"def\",\"password\":\"888\"},{\"id\":99, \"username\":\"ghi\",\"password\":\"999\"}]"

spring:
  application:
    name: user-service
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka1:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
